wisapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

# app_name = "wisapp"


urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_user, name='logout'),
    path('transfer', views.transfer, name='transfer'),
    path('parent_fine', views.fine_parent, name='parent_fine'),
    path('login/', views.sign_in, name='login'),
    path('account_status', views.acc_stat, name='account_status'),
    path('pupil_stat', views.pupil_stat, name='pupil_stat'),
    path('pupil_login/', views.pupil_sign_in, name='pupil_sign_in'),
    path('parent_stat', views.parent_stat, name='parent_stat'),
    path('parent_login/', views.parent_sign_in, name='parent_sign_in'),
    path('transfer_parent', views.transfer_parent, name='transfer_parent'),
    path('director_login/', views.director_login, name='director_login'),
    path('director_account', views.dir_stat, name='dir_account_status'),
    path('director_trans', views.dir_trans, name='dir_trans'),
    path('director_fine', views.dir_fine, name='dir_fine'),
    path('balance_user_login/', views.balance_user_sign_in, name='balance_user_sign_in'),
    path('balance_user_stat', views.balance_user_stat, name='balance_user_stat'),
    path('for_dirs', views.for_dirs, name='for_dirs_trans'),
    path('for_teachers', views.for_teaches, name='for_teachers_trans'),
    path('for_parents', views.for_pars, name='for_parents_trans'),
    path('public_api', views.p_api, name='p_api'),
    path('balance_add', views.s_b_add, name='s_b_add'),
    path('seller_login/', views.sell_login, name='sell_login'),
    path('seller_account', views.sell_stat, name='sell_stat'),
    path('web_app', views.web_app, name='web_app'),
    path('bot', views.bot, name='bot')
]

urlpatterns + static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

wisproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wisapp.urls'))
]

wisapp/models.py
from django.db import models
from django.conf import settings


# class Test(AbstractUser):
#     name = models.CharField(max_length=100)


class Grade(models.Model):
    gradeName = models.CharField(max_length=100, verbose_name="Класс", unique=True)
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return self.gradeName

    class Meta:
        verbose_name = "Классы"
        verbose_name_plural = "Классы"


class Seller(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Имя")
    lastName = models.CharField(max_length=100, verbose_name="Фамилия")
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    class Meta:
        verbose_name = "Продавцы"
        verbose_name_plural = "Продавцы"

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Имя")
    lastName = models.CharField(max_length=100, verbose_name="Фамилия")
    grade_t = models.ManyToManyField(Grade, verbose_name="Закрепленные классы")
    acc = models.IntegerField(null=True, blank=True, verbose_name="Баланс")
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return self.name + ' ' + self.lastName

    def grades(self):
        return "\n".join([g.gradeName for g in self.grade_t.all()])

    class Meta:
        verbose_name = "Учителя"
        verbose_name_plural = "Учителя"


class Pupil(models.Model):
    pupil_code = models.PositiveIntegerField(verbose_name='Код ученика', null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    lastName = models.CharField(max_length=100, verbose_name="Фамилия")
    name = models.CharField(max_length=100, verbose_name="Имя")
    grade_p = models.ForeignKey(Grade, on_delete=models.PROTECT, verbose_name="Класс")
    acc = models.IntegerField(null=True, blank=True, verbose_name="Баланс")
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return self.name + ' ' + self.lastName

    class Meta:
        verbose_name = "Ученики"
        verbose_name_plural = "Ученики"


class Parent(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Имя")
    lastName = models.CharField(max_length=100, verbose_name="Фамилия")
    child = models.ManyToManyField(Pupil, verbose_name="Ученик")
    acc = models.IntegerField(null=True, blank=True, verbose_name="Баланс")
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return self.name + ' ' + self.lastName

    def childes(self):
        return "\n".join([g.name for g in self.child.all()])

    class Meta:
        verbose_name = "Родители"
        verbose_name_plural = "Родители"


class DorZ(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Имя")
    lastName = models.CharField(max_length=100, verbose_name="Фамилия")
    acc = models.PositiveIntegerField(default=0, verbose_name="Баланс")
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return self.name + ' ' + self.lastName

    class Meta:
        verbose_name = "Директоры"
        verbose_name_plural = "Директоры"


class Transfers(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.PROTECT)
    transfer_grade = models.ForeignKey(Grade, on_delete=models.PROTECT, null=True)
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    point = models.PositiveIntegerField()

    def t_g(self):
        return "\n".join([g.name for g in self.pupil.all()])


class TransferHistory(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.PROTECT, verbose_name='Уччитель')
    transfer_grade = models.ForeignKey(Grade, on_delete=models.PROTECT, null=True, verbose_name='Класс')
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    point = models.PositiveIntegerField()
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def t_g(self):
        return "\n".join([g.name for g in self.pupil.all()])

    class Meta:
        verbose_name = "История переводов учителей"
        verbose_name_plural = "История переводов учителей"


class ParentTransfer(models.Model):
    parent_name = models.ForeignKey(Parent, on_delete=models.PROTECT)
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    point = models.PositiveIntegerField()

    def t_g(self):
        return "\n".join([g.name for g in self.pupil.all()])


class ParentTransferHistory(models.Model):
    parent_name = models.ForeignKey(Parent, on_delete=models.PROTECT, verbose_name='Родитель')
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    point = models.PositiveIntegerField()
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def t_g(self):
        return "\n".join([g.name for g in self.pupil.all()])

    class Meta:
        verbose_name = "История переводов родителей"
        verbose_name_plural = "История переводов родителей"


class PointTrans(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT)
    pupil = models.ForeignKey(Pupil, on_delete=models.PROTECT)
    point = models.IntegerField(default=0)
    point_sum = models.PositiveIntegerField(default=0)
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    class Meta:
        verbose_name = "Переводы учителей"
        verbose_name_plural = "Переводы учителей"


class Fine(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.PROTECT)
    transfer_grade = models.ForeignKey(Grade, on_delete=models.PROTECT, null=True)
    pupil = models.ManyToManyField(Pupil)
    fine_descr = models.CharField(max_length=250, null=True)
    point = models.PositiveIntegerField()


class FineHistory(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.PROTECT, verbose_name='Имя учителя')
    transfer_grade = models.ForeignKey(Grade, on_delete=models.PROTECT, null=True, verbose_name='Класс')
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    point = models.PositiveIntegerField()
    fine_descr = models.CharField(max_length=250, null=True, verbose_name='Описание штрафа')
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def f_p(self):
        return "\n".join([g.name for g in self.pupil.all()])

    class Meta:
        verbose_name = "История штрафов учителей"
        verbose_name_plural = "История штрафов учителей"


class PointTransParents(models.Model):
    teacher = models.ForeignKey(Parent, on_delete=models.PROTECT, verbose_name='Учитель')
    pupil = models.ForeignKey(Pupil, on_delete=models.PROTECT, verbose_name='Ученик')
    point = models.IntegerField(default=0)
    point_sum = models.PositiveIntegerField(default=0)
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    class Meta:
        verbose_name = "Переводы родителей"
        verbose_name_plural = "Переводы родителей"


class FineParent(models.Model):
    parent_name = models.ForeignKey(Parent, on_delete=models.PROTECT)
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    fine_descr = models.CharField(max_length=250, null=True, verbose_name='Описание штрафа')
    point = models.PositiveIntegerField()


class FineParentHistory(models.Model):
    parent_name = models.ForeignKey(Parent, on_delete=models.PROTECT, verbose_name='Родители')
    pupil = models.ManyToManyField(Pupil, verbose_name='Выберете ученика')
    fine_descr = models.CharField(max_length=250, null=True, verbose_name='Описание штрафа')
    point = models.PositiveIntegerField()
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def f_p(self):
        return "\n".join([g.name for g in self.pupil.all()])

    class Meta:
        verbose_name = "История штрафов родителей"
        verbose_name_plural = "История штрафов родителей"


class SchoolBalance(models.Model):
    balance = models.PositiveBigIntegerField(verbose_name='Баланс')

    class Meta:
        verbose_name = "Баланс школы"
        verbose_name_plural = "Баланс школы"


class DorZTransfer(models.Model):
    dorz_name = models.ForeignKey(DorZ, on_delete=models.PROTECT)
    pupil = models.ManyToManyField(Pupil)
    point = models.PositiveIntegerField()

    def pupil_show(self):
        return "\n".join([g.name for g in self.pupil.all()])


class DorZTransferHistory(models.Model):
    dorz_name = models.ForeignKey(DorZ, on_delete=models.PROTECT, verbose_name='Директор')
    pupil = models.ManyToManyField(Pupil, verbose_name='Ученик')
    point = models.PositiveIntegerField()
    data = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def pupil_show(self):
        return "\n".join([g.name for g in self.pupil.all()])

    class Meta:
        verbose_name = "История переводов завучы и директоры"
        verbose_name_plural = "История переводов завучы и директоры"


class FineDorZ(models.Model):
    dorz_name = models.ForeignKey(DorZ, on_delete=models.PROTECT)
    pupil = models.ManyToManyField(Pupil)
    fine_descr = models.CharField(max_length=250, null=True)
    point = models.PositiveIntegerField()


class FineDorZHistory(models.Model):
    dorz_name = models.ForeignKey(DorZ, on_delete=models.PROTECT, verbose_name='Директор')

wisapp/forms.py
from django import forms
from . import models


class TransferForm(forms.ModelForm):
    class Meta:
        model = models.Transfers
        fields = ['teacher_name', 'transfer_grade', 'pupil', 'point']


class TransferHistoryForm(forms.ModelForm):
    class Meta:
        model = models.TransferHistory
        fields = ['teacher_name', 'transfer_grade', 'pupil', 'point']


class ParentTransferForm(forms.ModelForm):
    class Meta:
        model = models.ParentTransfer
        fields = ['parent_name', 'pupil', 'point']


class ParentTransferHistoryForm(forms.ModelForm):
    class Meta:
        model = models.ParentTransferHistory
        fields = ['parent_name', 'pupil', 'point']


class FineForm(forms.ModelForm):
    class Meta:
        model = models.Fine
        fields = '__all__'


class FineHistoryForm(forms.ModelForm):
    class Meta:
        model = models.FineHistory
        fields = '__all__'


class FineParentForm(forms.ModelForm):

    class Meta:
        model = models.FineParent
        fields = '__all__'


class FineParentHistoryForm(forms.ModelForm):
    class Meta:
        model = models.FineParentHistory
        fields = '__all__'


class DorZTransferForm(forms.ModelForm):
    class Meta:
        model = models.DorZTransfer
        fields = '__all__'


class DorZTransferHistoryForm(forms.ModelForm):
    class Meta:
        model = models.DorZTransferHistory
        fields = '__all__'


class DorZFineForm(forms.ModelForm):
    class Meta:
        model = models.FineDorZ
        fields = '__all__'


class DorZTFineHistoryForm(forms.ModelForm):
    class Meta:
        model = models.FineDorZHistory
        fields = '__all__'


class SuperUTransDForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransD
        fields = '__all__'


class SuperUTransDHForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransDH
        fields = '__all__'


class SuperUTransTForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransT
        fields = '__all__'


class SuperUTransTHForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransTH
        fields = '__all__'


class SuperUTransPForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransP
        fields = '__all__'


class SuperUTransPHForm(forms.ModelForm):
    class Meta:
        model = models.SuperUTransPH
        fields = '__all__'


class BalanceAddForm(forms.ModelForm):
    class Meta:
        model = models.SchoolBalanceAdd
        fields = '__all__'

wisapp/templates/wisapp/balance_add.html
{% extends 'wisapp/profile_base.html' %}
{% block url %}
    <a class="nav-item nav-link" href="{% url 'balance_user_stat' %}">BOSH SAHIFA<span class="sr-only">(current)</span></a>
{% endblock %}
{% block headcontent %}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');

            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(170, 95, 57);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }

            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }

            #side_panel::-webkit-scrollbar {
                width: 7px;
            }
            #side_panel::-webkit-scrollbar:hover {
                width: 12px;
            }
            #side_panel::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }

            body {font-family: Arial;}

            /* Style the tab */
            .tab {
              overflow: hidden;
              border: 1px solid #ccc;
              background-color: #f1f1f1;
            }

            /* Style the buttons inside the tab */
            .tab button {
              background-color: inherit;
              float: left;
              border: none;
              outline: none;
              cursor: pointer;
              padding: 14px 16px;
              transition: 0.3s;
              font-size: 17px;
            }

            /* Change background color of buttons on hover */
            .tab button:hover {
              background-color: #ddd;
            }

            /* Create an active/current tablink class */
            .tab button.active {
              background-color: #ccc;
            }

            /* Style the tab content */
            .tabcontent {
              display: none;
              padding: 6px 12px;
              border: 1px solid #ccc;
              border-top: none;
            }

            .add__flex{

                    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
            }

            .form-control2{
                   width: 70%;
            }
        </style>
        <script>
            window.addEventListener('DOMContentLoaded', function() {
                var select = document.querySelector('#main'),
                hide = document.querySelectorAll('.hide');
                function change()
                {
                    [].forEach.call(hide, function(el) {
                        var add = el.classList.contains(select.value) ? "add" : "remove"
                        el.classList[add]('show');
                    });
                }
                select.addEventListener('change', change);
                  change()
            });
        </script>
{% endblock %}
{% block bodycontent %}
<main class="wrapper">
    <form class="add__flex" action="" method="post">
    {% csrf_token %}
    <select name="user" required="" id="id_user" hidden>
        <option value="{{ curr_user.id }}" selected>{{ curr_user.name }}</option>
    </select>
    <label for="id_point"> Wispoint </label>
    <input type="number" name="point" min="1" max="9223372036854775807" required="" class="form-control2" id="id_point">

    <button class="transfer-button" type="submit">qoshish</button>
</form>

</main>
<br>
<br>
<br>


{% endblock %}


{% block scriptcontent %}
        <script>
            $(".current").removeClass("current");
            $("#transfer").addClass("current");
            $("input").addClass("form-control");
            $("label").prepend("<br>")
        </script>

        <script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

const nodeList= document.querySelectorAll(".haha");
nodeList[0].setAttribute("required", "required");
</script>
{% endblock %}

wisapp/templates/wisapp/balance_user_stat.html
{% extends 'wisapp/profile_base.html' %}
{% block url %}
    <a class="nav-item nav-link" href="{% url 'balance_user_stat' %}">BOSH SAHIFA<span class="sr-only">(current)</span></a>
    {% endblock %}
{% block headcontent %}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');

            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(170, 95, 57);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }

            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }

            #side_panel::-webkit-scrollbar {
                width: 7px;
            }
            #side_panel::-webkit-scrollbar:hover {
                width: 12px;
            }
            #side_panel::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }

            body {font-family: Arial;}

            /* Style the tab */
            .tab {
              overflow: hidden;
              border: 1px solid #ccc;
              background-color: #f1f1f1;
            }

            /* Style the buttons inside the tab */
            .tab button {
              background-color: inherit;
              float: left;
              border: none;
              outline: none;
              cursor: pointer;
              padding: 14px 16px;
              transition: 0.3s;
              font-size: 17px;
            }

            /* Change background color of buttons on hover */
            .tab button:hover {
              background-color: #ddd;
            }

            /* Create an active/current tablink class */
            .tab button.active {
              background-color: #ccc;
            }

            /* Style the tab content */
            .tabcontent {
              display: none;
              padding: 6px 12px;
              border: 1px solid #ccc;
              border-top: none;
            }

            .profile_buttons_balance_user{
                width:100% !important;
            }
        </style>
        <script>
            window.addEventListener('DOMContentLoaded', function() {
                var select = document.querySelector('#main'),
                hide = document.querySelectorAll('.hide');
                function change()
                {
                    [].forEach.call(hide, function(el) {
                        var add = el.classList.contains(select.value) ? "add" : "remove"
                        el.classList[add]('show');
                    });
                }
                select.addEventListener('change', change);
                  change()
            });
        </script>
{% endblock %}
{% block bodycontent %}
    <main class="wrapper">
        <section id="welcome_post" class="col-12">
            <div align="center">
            <h2>Hush kelibsiz, <span id="prof_name">{{ curr_user.name }}{{ curr_user.lastName }}</span> </h2>

                <div class="text-center curr_bal my_ballance">
                <h4>Balansingizdagi mavjud Wispointlar</h4>
                <h1 id="curr_bal" class="btn-success wispoints_amount">{{ school.balance }}</h1>
            </div>

                <div class="row profile_buttons profile_buttons_balance_user">
                    <div class="col-md-3">
                         <a href="{% url 's_b_add' %}"><button  class="transfer_button">Maytab balansi</button></a>
                    </div>

                    <div class="col-md-3">
                         <a href="{% url 'for_dirs_trans' %}"><button  class="transfer_button">Direktorga otkazish</button></a>
                        </div>

                     <div class="col-md-3">
                            <a href="{% url 'for_teachers_trans' %}"><button  class="transfer_button">Ustozlarga otkazish</button></a>
                         </div>

                    <div class="col-md-3">
                          <a href="{% url 'for_parents_trans' %}"><button  class="transfer_button">Ota-onaga otkazish</button></a>
                    </div>

                </div>


            <br>

            <br>
         </div>
        </section>
    </main>
{% endblock %}

wisapp/templates/wisapp/index.html
{% extends 'wisapp/base.html' %}

{% block stylecontent %}
    <style>

        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }

        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }

        .my_button {
             width: 50%;
            background: #ffffff;
            margin: 0 auto;
            border: none;
            border-radius: 50px;
            color: #000000;
            padding: 15px;
            box-shadow: 0px 3px 15px 0.2px rgb(0 0 0 / 40%);
            display: block;
        }

        .my_button:hover {
            cursor: pointer;
            background: rgb(167 167 167 / 40%);
            color: #000000;
        }

        .row{
            width: 40%;
            margin: 0 auto;
        }

        html{
        height: 100%;
        }

        body{
            display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
        }

        @media(max-width:734px){
            .row{
            width:100%;
            }
        }
    </style>
{% endblock %}


{% block bodycontent %}



    <div class="container">
        <div class="row">

            <a class="btn btn-primary btn-block my_button  col-12" href="{% url 'director_login' %}"> <i class="fa fa-sign-in"></i> Direktor</a>

        <a class="btn btn-primary btn-block my_button col-12" href="{% url 'login' %}"> <i class="fa fa-sign-in"></i> O'qituvchi</a>

        <a class="btn btn-primary btn-block my_button col-12" href="{% url 'pupil_sign_in' %}">  <i class="fa fa-sign-in"></i> O'quvchi</a>

        <a class="btn btn-primary btn-block my_button col-12" href="{% url 'parent_sign_in' %}"> <i class="fa fa-sign-in"></i> Ota-ona</a>

        </div>
    </div>


{% endblock %}